project_id = "twefckgvkebwduzilhpz"

[functions.send-order-confirmation]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
